name: Check Style

on: [push, pull_request]

jobs:

  style:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master

    - name: Only fetch Style PHP submodule
      run: git submodule update --init -- .style

    - name: Install latest PHP-CS-Fixer
      run: wget https://cs.symfony.com/download/php-cs-fixer-v3.phar -O php-cs-fixer

    - name: Run Checks
      run: php php-cs-fixer fix --config=.style/.php-cs-fixer.php -v --dry-run --allow-risky=yes .
